from formula.variable import Variable

a = Variable("a")
b = Variable("b")
c = Variable("c")
d = Variable("d")
e = Variable("e")
f = Variable("f")
g = Variable("g")
h = Variable("h")
i = Variable("i")
j = Variable("j")
k = Variable("k")
l = Variable("l") # noqa: E741
m = Variable("m")
n = Variable("n")
o = Variable("o")
p = Variable("p")
q = Variable("q")
r = Variable("r")
s = Variable("s")
t = Variable("t")
u = Variable("u")
v = Variable("v")
w = Variable("w")
x = Variable("x")
y = Variable("y")
z = Variable("z")